#pragma config(Motor,  port2,           leftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightMotor1,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		//Controlling wheel motors
		motor[leftMotor1] = vexRT[Ch3];
		motor[leftMotor2] = vexRT[Ch3];
		motor[rightMotor1] = vexRT[Ch2];
		motor[rightMotor2] = vexRT[Ch2];
		/*
		if (vexRT[Btn5U]) {
			motor[liftMotor] = 255
		}
		if (vexRT[Btn5D]) {
			motor[liftMotor] = -255
		}
	}
	for (int x = 1; x<99; x++) {
		motor[leftMotor1] = x;
		motor[leftMotor2] = x;
		motor[rightMotor1] = x;
		motor[rightMotor2] = x;
	}
	*/
	}
}
