#pragma config(Motor,  port2,           lbw,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lfw,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rbw,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rfw,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           la,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ra,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[lbw] = 255;
	motor[lfw] = 255;
	motor[rbw] = 245;
	motor[rfw] = 245;
	delay(2440);
	motor[lbw] = 0;
	motor[lfw] = 0;
	motor[rbw] = 0;
	motor[rfw] = 0;
	motor[la] = 255;
	motor[ra] = 255;
	delay(1900);
	motor[lbw] = 255;
	motor[lfw] = 255;
	motor[rbw] = 255;
	motor[rfw] = 255;
	motor[la] = 0;
	motor[ra] = 0;
	delay(740);
	motor[lbw] = 0;
	motor[lfw] = 0;
	motor[rbw] = 0;
	motor[rfw] = 0;
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	while (vexRT[Btn5U])
  	{
  		motor[la] = 255;
  		motor[ra] = 255;
  	}
  	while (vexRT[Btn5D])
  	{
  		motor[la] = -255;
  		motor[ra] = -255;
  	}
  	motor[la] = 0;
  	motor[ra] = 0;
  	motor[lbw] = vexRT[Ch3];
  	motor[lfw] = vexRT[Ch3];
  	motor[rbw] = vexRT[Ch2];
   	motor[rfw] = vexRT[Ch2];
   	if (vexRT[Btn8L])
   	{
			motor[lbw] = 255;
			motor[lfw] = 255;
			motor[rbw] = 245;
			motor[rfw] = 245;
			delay(2440);
			motor[lbw] = 0;
			motor[lfw] = 0;
			motor[rbw] = 0;
			motor[rfw] = 0;
			motor[la] = 255;
			motor[ra] = 255;
			delay(1900);
			motor[lbw] = 255;
			motor[lfw] = 255;
			motor[rbw] = 255;
			motor[rfw] = 255;
			motor[la] = 0;
			motor[ra] = 0;
			delay(740);
			motor[lbw] = 0;
			motor[lfw] = 0;
			motor[rbw] = 0;
			motor[rfw] = 0;
		}
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
